# Generated by Django 4.2.16 on 2024-12-12 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 12, 20, 21, 46, 719979), verbose_name='Опубликована'),
        ),
    ]
