# Generated by Django 4.2.16 on 2024-12-18 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_alter_cartitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 18, 19, 56, 50, 414632), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 18, 19, 56, 50, 414632), verbose_name='Дата комментария'),
        ),
    ]
